#define INPUT_SIZE 16
#define FILTER_SIZE 3
#define POOL_SIZE 2
#define STRIDE_SIZE 2
#define OUTPUT_SIZE (INPUT_SIZE - FILTER_SIZE + 1)
#define POOL_OUTPUT_SIZE (OUTPUT_SIZE / POOL_SIZE)
#define COMPUTE_LOSS_SIZE (POOL_OUTPUT_SIZE * POOL_OUTPUT_SIZE)
#define LEARNING_RATE 0.01